# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from res_rc import *


class Ui_Form(object):
        def setupUi(self, Form):
                Form.setObjectName("Form")
                Form.setEnabled(True)
                Form.resize(1008, 657)
                self.widget = QtWidgets.QWidget(Form)
                self.widget.setGeometry(QtCore.QRect(-130, -110, 1321, 1001))
                self.widget.setObjectName("widget")
                self.textEdit = QtWidgets.QTextEdit(self.widget)
                self.textEdit.setGeometry(QtCore.QRect(140, 670, 961, 91))
                self.textEdit.setStyleSheet("background-color: rgb(0,0,0,100);\n"
        "border-radius: 20px;\n"
        "")
                self.textEdit.setObjectName("textEdit")
                self.pushButton = QtWidgets.QPushButton(self.widget)
                self.pushButton.setGeometry(QtCore.QRect(290, 700, 61, 31))
                self.pushButton.setStyleSheet("QPushButton{\n"
        "background-color: rgba(0,0,0,0);\n"
        "border: 2px solid rgba(255,33,100,230);\n"
        "border-radius: 10px;\n"
        "}")
                self.pushButton.setObjectName("pushButton")
                self.pushButton_2 = QtWidgets.QPushButton(self.widget)
                self.pushButton_2.setGeometry(QtCore.QRect(360, 700, 61, 31))
                self.pushButton_2.setStyleSheet("QPushButton{\n"
        "background-color: rgba(0,0,0,0);\n"
        "border: 2px solid rgba(255,33,100,230);\n"
        "border-radius: 10px;\n"
        "\n"
        "}")
                self.pushButton_2.setIconSize(QtCore.QSize(16, 16))
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_3 = QtWidgets.QPushButton(self.widget)
                self.pushButton_3.setGeometry(QtCore.QRect(430, 700, 61, 31))
                self.pushButton_3.setStyleSheet("QPushButton{\n"
        "background-color: rgba(0,0,0,0);\n"
        "border: 2px solid rgba(255,33,100,230);\n"
        "border-radius: 10px;\n"
        "\n"
        "}")
                self.pushButton_3.setObjectName("pushButton_3")
                self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
                self.textEdit_2.setGeometry(QtCore.QRect(130, 110, 1011, 661))
                self.textEdit_2.setStyleSheet("background-color: rgba(255, 193, 179, 0.60);\n"
        "border-radius: 1px;\n"
        "")
                self.textEdit_2.setObjectName("textEdit_2")
                self.label = QtWidgets.QLabel(self.widget)
                self.label.setGeometry(QtCore.QRect(600, 610, 1221, 941))
                self.label.setStyleSheet("QLabel{\n"
        "\n"
        "}")
                self.label.setText("")
                self.label.setObjectName("label")
                self.listWidget = QtWidgets.QListWidget(self.widget)
                self.listWidget.setGeometry(QtCore.QRect(340, 130, 731, 451))
                self.listWidget.setObjectName("listWidget")
                self.textEdit_3 = QtWidgets.QTextEdit(self.widget)
                self.textEdit_3.setGeometry(QtCore.QRect(120, 110, 171, 551))
                self.textEdit_3.setStyleSheet("background-color: rgba(255, 193, 179, 1);\n"
        "\n"
        "")
                self.textEdit_3.setObjectName("textEdit_3")
                self.textEdit_4 = QtWidgets.QTextEdit(self.widget)
                self.textEdit_4.setGeometry(QtCore.QRect(120, 660, 1021, 151))
                self.textEdit_4.setStyleSheet("background-color: rgba(255, 193, 179, 1);")
                self.textEdit_4.setObjectName("textEdit_4")
                self.horizontalSlider = QtWidgets.QSlider(self.widget)
                self.horizontalSlider.setGeometry(QtCore.QRect(180, 690, 101, 51))
                self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
                self.horizontalSlider.setObjectName("horizontalSlider")
                self.pushButton_4 = QtWidgets.QPushButton(self.widget)
                self.pushButton_4.setGeometry(QtCore.QRect(600, 590, 91, 51))
                self.pushButton_4.setStyleSheet("QPushButton{\n"
        "background-color: rgba(0,0,0,0);\n"
        "border: 2px solid rgba(255,33,100,230);\n"
        "border-radius: 10px;\n"
        "\n"
        "}")
                self.pushButton_4.setObjectName("pushButton_4")
                self.pushButton_5 = QtWidgets.QPushButton(self.widget)
                self.pushButton_5.setGeometry(QtCore.QRect(710, 590, 91, 51))
                self.pushButton_5.setStyleSheet("QPushButton{\n"
        "background-color: rgba(0,0,0,0);\n"
        "border: 2px solid rgba(255,33,100,230);\n"
        "border-radius: 10px;\n"
        "\n"
        "}")
                self.pushButton_5.setObjectName("pushButton_5")
                self.textEdit_5 = QtWidgets.QTextEdit(self.widget)
                self.textEdit_5.setGeometry(QtCore.QRect(550, 580, 301, 70))
                self.textEdit_5.setStyleSheet("background-color: rgb(0,0,0,100);\n"
        "border-radius: 20px;\n"
        "")
                self.textEdit_5.setObjectName("textEdit_5")
                self.verticalSlider = QtWidgets.QSlider(self.widget)
                self.verticalSlider.setGeometry(QtCore.QRect(1080, 130, 21, 451))
                self.verticalSlider.setStyleSheet("QSlider::groove:vertical{\n"
        "background-color: rgba(0,0,0,100);\n"
        "border-radius: 10px\n"
        "}\n"
        "\n"
        "QSlider::handle:vertical{\n"
        "width: 10px;\n"
        "height: 30px;\n"
        "padding: 5px;\n"
        "background-color: rgba(255,33,100,230);\n"
        "border-radius: 10px;\n"
        "\n"
        "}")
                self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
                self.verticalSlider.setObjectName("verticalSlider")
                self.textEdit_2.raise_()
                self.label.raise_()
                self.listWidget.raise_()
                self.textEdit_3.raise_()
                self.textEdit_4.raise_()
                self.textEdit.raise_()
                self.pushButton_3.raise_()
                self.pushButton_2.raise_()
                self.pushButton.raise_()
                self.horizontalSlider.raise_()
                self.textEdit_5.raise_()
                self.pushButton_4.raise_()
                self.pushButton_5.raise_()
                self.verticalSlider.raise_()

                self.retranslateUi(Form)
                QtCore.QMetaObject.connectSlotsByName(Form)

        def retranslateUi(self, Form):
                _translate = QtCore.QCoreApplication.translate
                Form.setWindowTitle(_translate("Form", "")) # изменить название окна
                self.pushButton.setText(_translate("Form", "<"))
                self.pushButton_2.setText(_translate("Form", "play"))
                self.pushButton_3.setText(_translate("Form", ">"))
                self.pushButton_4.setText(_translate("Form", "Add"))
                self.pushButton_5.setText(_translate("Form", "Remove"))
if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())